# Generated by Django 4.0.6 on 2022-08-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Адрес пункта выдачи')),
            ],
            options={
                'verbose_name': 'Адрес пункта выдачи',
                'verbose_name_plural': 'Адреса пункта выдачи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('issuing_addresses_file', models.FileField(upload_to='media')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('point_of_issue', models.ManyToManyField(to='order.pointofissue', verbose_name='Пункт выдачи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
