# Generated by Django 4.0.6 on 2022-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Адрес пункта выдачи')),
            ],
            options={
                'verbose_name': 'Адрес пункта выдачи',
                'verbose_name_plural': 'Адреса пункта выдачи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('product_type', models.CharField(max_length=255, verbose_name='Тип продукта')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('addresses_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл с адресами')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('addresses', models.ManyToManyField(to='order.pointofissue', verbose_name='Адреса пункта выдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
